name: better_flutter
description: "Better Flutter provides custom UI components for building Flutter applications faster and more efficiently than with built-in Flutter widgets."
version: 1.0.0
homepage: https://github.com/eliseyOzerov/better_flutter

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  better_extensions: ^1.0.0
  flutter:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
